# Generated by Django 3.1.2 on 2021-08-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210829_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
