# Generated by Django 3.1.2 on 2021-09-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210905_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='custmansys\\BASE_DIR\\static\\images\t.png', null=True, upload_to=''),
        ),
    ]
