# Generated by Django 3.1.2 on 2021-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kindpng.com%2Fimgv%2Fiwoxbb_user-profile-default-image-png-clipart-png-download%2F&psig=AOvVaw0SPaKalEAuIROKLW7Mh4Or&ust=1630933860704000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJCPi5705_ICFQAAAAAdAAAAABAI', null=True, upload_to=''),
        ),
    ]
