# Generated by Django 3.1.2 on 2021-09-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210905_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
